name: Check PR
on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Lint
        run: yarn lint

      - name: Tsc
        run: yarn tsc
